import { Travelers } from "~/lib/data/Travelers";
import { Characters } from "../data/Characters";
import { ICharacterViewModel } from "../interfaces/ICharacterViewModel";

// This will be used to display the character cards
export const charactersViewModel: ICharacterViewModel[] = [
  Characters.kokomi,
  Characters.aloy,
  Characters.sara,
  Characters.raiden,
  Characters.yoimiya,
  Characters.sayu,
  Characters.ayaka,
  Travelers.traveler_electro,
  Characters.kazuha,
  Characters.eula,
  Characters.yanfei,
  Characters.rosaria,
  Characters.hu_tao,
  Characters.xiao,
  Characters.ganyu,
  Characters.albedo,
  Characters.zhongli,
  Characters.xinyan,
  Characters.tartaglia,
  Characters.diona,
  Characters.klee,
  Characters.venti,
  Characters.keqing,
  Characters.mona,
  Characters.qiqi,
  Characters.diluc,
  Characters.jean,
  Characters.sucrose,
  Characters.chongyun,
  Characters.noelle,
  Characters.bennett,
  Characters.fischl,
  Characters.ningguang,
  Characters.xingqiu,
  Characters.beidou,
  Characters.xiangling,
  Characters.razor,
  Characters.barbara,
  Characters.lisa,
  Characters.kaeya,
  Characters.amber,
  Travelers.traveler_geo,
  Travelers.traveler_anemo,
];
