// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CharacterCard: typeof import('./src/components/character/CharacterCard.vue')['default']
    CharacterPortrait: typeof import('./src/components/character/CharacterPortrait.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    IconWithText: typeof import('./src/components/IconWithText.vue')['default']
    RarityStars: typeof import('./src/components/RarityStars.vue')['default']
    TheClampedText: typeof import('./src/components/TheClampedText.vue')['default']
    TheLeftPanel: typeof import('./src/components/BuildCharacter/TheLeftPanel.vue')['default']
    XLContainer: typeof import('./src/components/XLContainer.vue')['default']
    XXLContainer: typeof import('./src/components/XXLContainer.vue')['default']
  }
}

export { }
